### ISSUE TITLE
Adding gamair data

### ISSUE THREAD

**Issue by IlanReinstein** [JuliaStats/RDatasets.jl#102]
I would like to add the datasets from Simon Wood's book on GAM's using R.

I've already used Vincent's (Rdatasets) package to create documentation and have the files locally ready to add.

**Comment by IlanReinstein** [comment]
Submitted PR #103

**Comment by tlienart** [comment]
Hello @IlanReinstein this is now merged (finally), though it breaks some test in terms of documented datasets: 
https://github.com/JuliaStats/RDatasets.jl/blob/73f96a083d24f6adfc756914c0b26e0225f28692/test/datasets.jl#L13-L14 

would you be willing to look into this? 

(sorry I'm not a main maintainer so trying to figure things out along the way...)
