### ISSUE TITLE
no method matching getindex(::Void, ::String) on missing RData

### ISSUE THREAD

**Issue by colbec** [JuliaStats/RDatasets.jl#44]
Using Julia 0.6 with RDatatsets installed and passing tests but no RData installed, if I call for a dataset RDatasets correctly finds I have no RData and volunteers to install it for me. This appears to happen ok but ends with 

```
should we install RData for you? (y/n):
y
INFO: Start installing RData...
INFO: Installing RData v0.0.4
INFO: Building Rmath
INFO: Package database updated
ERROR: MethodError: no method matching getindex(::Void, ::String)
 in dataset(::String, ::String) at /home/colin/.julia/v0.6/RDatasets/src/dataset.jl:6
```

RData seems to be correctly installed since now I can call for a dataset and it will display.
I tried checkout of RDatasets and same behaviour.
Also tried Pkg.rm("RData") and the behaviour repeated.
On Julia 0.4.6 I get a depwarn error which is quite different, but will hold off on that report.

**Comment by asinghvi17** [comment]
I believe this is not an issue any more?
