### ISSUE TITLE
Move to JuliaStats or JuliaData

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/RDatasets.jl#46]
This needs some 0.6 updates, and there are a few open PRs. Any chance you would be willing to move it?

**Comment by quinnj** [comment]
Seems like JuliaData would be a good home for this. I've been meaning to implement the DataStreams framework for this package anyway.

**Comment by randyzwitch** [comment]
What's to address? We just updated the package to support 0.6/DataFrames 0.11. Moving the package doesn't mean more updates, just a different location.

**Comment by rofinn** [comment]
Yeah, if there are enough people who can merge PRs and tag releases then I don't see a lot of benefit in moving it.
