### ISSUE TITLE
datasets() gives harmless(?) parsing warning

### ISSUE THREAD

**Issue by ohadle** [JuliaStats/RDatasets.jl#60]
```julia
julia> ds = RDatasets.datasets()
warning: failed parsing String on row=161, col=3, error=INVALID: OK, QUOTED, DELIMITED, INVALID_DELI
MITER
733×5 DataFrame
...

julia> ds[161, 3]
"Data from A.-M. Guerry, \\"
```

**Comment by alejandromerchan** [comment]
I've seen those warning popping up in the new version of CSV.jl. They are harmless, but show you possible problems with your data. In your case, for example, "\" is the default escape character, so the parse probably doesn't know how to deal with it. That's my guess. I submitted an issue to CSV, and they might implement a kwarg that silences the warnings if needed.
