### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaStats/RDatasets.jl#72]
It seems like Julia.Registrator isn't registered yet:

https://github.com/johnmyleswhite/RDatasets.jl/commit/fe25c8111a980942ff5ab8e675507e084118979f

(The bot usually answers comments, if its installed)

Would be nice to install it:
https://github.com/JuliaRegistries/Registrator.jl

@johnmyleswhite, would it make sense to transfer the repository to e.g. JuliaIO or JuliaData?

**Comment by SimonDanisch** [comment]
bump

**Comment by mkborregaard** [comment]
@johnmyleswhite is it time to fork this repo somewhere else and reregister the fork?

**Comment by SimonDanisch** [comment]
I'd say we wait until end of this week - I really, really want to tag Makie until then.
@randyzwitch do you know the status on this?

**Comment by SimonDanisch** [comment]
bump - please, this has been dragging out the Makie release for more than half a month now!

**Comment by asinghvi17** [comment]
This will be fixed when the new version is tagged (as soon as the PR to change the URL in General is merged).
