### ISSUE TITLE
Install CompatHelper?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaStats/RDatasets.jl#82]

**Comment by asinghvi17** [comment]
Is that just copying the workflow file?

**Comment by DilumAluthge** [comment]
Yep. Full instructions here: https://github.com/bcbi/CompatHelper.jl/blob/master/README.md#installation

I tried to do it myself and make a pull request from a fork, but I don’t think they allow pull requests from forks to create brand new workflows.
